### ISSUE TITLE
Error when exporting rules using toJSON()

### ISSUE THREAD

**Issue by tuananh** [mithunsatheesh/node-rules#61]
```
node_modules/node-rules/lib/node-rules.js:94
                _rule.call(session, API);
                      ^

TypeError: _rule.call is not a function
    at FnRuleLoop (/Users/anh/code/test/node_modules/node-rules/lib/node-rules.js:94:23)
    at RuleEngine.execute (/Users/anh/code/test/node_modules/node-rules/lib/node-rules.js:101:11)
    at Object.<anonymous> (/Users/anh/code/test/utils/ruleEngine.js:29:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
```

The code: I just copied the example.

```
const RuleEngine = require('node-rules')

//define the rules
var rules = [{
    "condition": function(R) {
        R.when(this && (this.transactionTotal < 500))
    },
    "consequence": function(R) {
        this.result = false
        R.stop()
    }
}]

//sample fact to run the rules on
var fact = {
    "name":"user4",
    "application":"MOB2",
    "transactionTotal":400,
    "cardType":"Credit Card",
}

//initialize the rule engine
var R = new RuleEngine(rules)

var store = R.toJSON();
console.log(store)

//Now pass the fact on to the rule engine for results
R.execute(fact,function(result){
    
    if(result.result)
        console.log("Payment Accepted")
    else
        console.log("Payment Rejected")

})
```

**Comment by Deamoner** [comment]
Bump getting this as well.

**Comment by flgarrid** [comment]
The toJSON function directly modifies the "RuleEngine.rules" object to create the string, thus modifying all RuleEngine rules when its done (all functions become strings).

To solve that, you have to call R.fromJSON(store) after R.toJSON():

```
var R = new RuleEngine(rules)

var store = R.toJSON();
console.log(store)

**R.fromJSON(store)**

```

**Comment by mendaXXXX** [comment]
As flgarrid@ pointed, a subsequent fromJSON call revives the rules back.
https://runkit.com/mendaxxxx/5afaedaefd2f1200123b5a45

But its an unexpected behavior from the rule engine to change behavior on `toJSON` call.

**Comment by mendaXXXX** [comment]
Current logic operates on the attribiutes of the rule engine.

https://github.com/mithunsatheesh/node-rules/blob/master/lib/node-rules.js#L131-L144
```
RuleEngine.prototype.toJSON = function() {
        var rules = this.rules;
        if (rules instanceof Array) {
            rules = rules.map(function(rule) {
                rule.condition = rule.condition.toString();
                rule.consequence = rule.consequence.toString();
                return rule;
            });
        } else if (typeof(rules) != "undefined") {
            rules.condition = rules.condition.toString();
            rules.consequence = rules.consequence.toString();
        }
        return rules;
    };
```

**Comment by jackie-chan** [comment]
When I run this, I'm getting an error that the toJSON() is not a function
`var store = R.toJSON();
console.log(store)

R.fromJSON(store)`
I've pretty much just run the example code that was provided in the examples

**Comment by mithunsatheesh** [comment]
You would need to use versions less than 5.0.0 to use export and import rule features.
As per the security report in #84, we have removed the support for export import in the latest stable version.

**Comment by jackie-chan** [comment]
> You would need to use versions less than 5.0.0 to use export and import rule features.
> As per the security report in #84, we have removed the support for export import in the latest stable version.

Perfect. Thanks!
