### ISSUE TITLE
How does it work for Objects with nested elements?

### ISSUE THREAD

**Issue by sriharsha9** [mithunsatheesh/node-rules#74]
I have my JSON Object as shown below 
```
var fact = {
        "testList": [{
            "test" : {
                "name" : "Steelers"
            }
        }]
 };
```
Trying to filter based on a return value of true.
```
var rule = {
        "condition": (ruleEngine) => {
            ruleEngine.when(this.testList[0].test.name === "Steelers" );
        },
        "consequence": (ruleEngine) => {
            this.result = true;
            ruleEngine.stop();
        }
    };
```

I am seeing the below error 
```
mscorlib: TypeError: Cannot read property '0' of undefined
    at Object.condition (D:\home\site\wwwroot\RulesEngine\index.js:12:46)
    at FnRuleLoop (D:\home\site\wwwroot\RulesEngine\node_modules\node-rules\lib\node-rules.js:98:23)
    at RuleEngine.execute (D:\home\site\wwwroot\RulesEngine\node_modules\node-rules\lib\node-rules.js:105:11)
    at module.exports (D:\home\site\wwwroot\RulesEngine\index.js:39:16)
    at D:\Program Files (x86)\SiteExtensions\Functions\1.0.11820\bin\azurefunctions\functions.js:106:24.

```

Not sure what I am missing here. Does this library support nested objects as facts?

**Comment by m13n** [comment]
This is due to the arrow functions loosing context of `this`.  

Please find the below run kit example where this works fine.
https://runkit.com/mendaxxxx/5afaedaefd2f1200123b5a45
