### ISSUE TITLE
Module build failed (from ./node_modules/babel-loader/lib/index.js)

### ISSUE THREAD

**Issue by mithunsatheesh** [mithunsatheesh/node-rules#94]
Running below script to generate the minified file results in error:

    npm run-script build

````
ERROR in ./index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-preset-env' from '/Users/smithun/Desktop/NodeRules/node-rules'
    at Function.resolveSync [as sync] (/Users/smithun/Desktop/NodeRules/node-rules/node_modules/@babel/core/node_modules/resolve/lib/sync.js:89:15)
    at resolveStandardizedName (/Users/smithun/Desktop/NodeRules/node-rules/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (/Users/smithun/Desktop/NodeRules/node-rules/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (/Users/smithun/Desktop/NodeRules/node-rules/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (/Users/smithun/Desktop/NodeRules/node-rules/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /Users/smithun/Desktop/NodeRules/node-rules/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/smithun/Desktop/NodeRules/node-rules/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/smithun/Desktop/NodeRules/node-rules/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/smithun/Desktop/NodeRules/node-rules/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
````

**Comment by mithunsatheesh** [comment]
Related to https://github.com/babel/babel-loader/issues/616

**Comment by mithunsatheesh** [comment]
````
npm run-script build

> node-rules@5.1.0 build /Users/smithun/Desktop/NodeRules/node-rules
> webpack

(node:15592) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:15592) [DEP_WEBPACK_COMPILATION_CACHE] DeprecationWarning: Compilation.cache was removed in favor of Compilation.getCache()
[webpack-cli] Compilation finished
asset node-rules.min.js 22.4 KiB [compared for emit] (name: main)
runtime modules 344 bytes 2 modules
cacheable modules 97 KiB
  modules by path ./node_modules/ 92.3 KiB
    ./node_modules/lodash.isequal/index.js 48.2 KiB [built] [code generated]
    ./node_modules/lodash.clonedeep/index.js 44 KiB [built] [code generated]
  ./index.js 135 bytes [built] [code generated]
  ./lib/node-rules.js 4.62 KiB [built] [code generated]
webpack 5.4.0 compiled successfully in 1706 ms
````
